# Generated by Django 5.2 on 2025-05-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_rating_unique_together_bookmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at', '-author', '-title']},
        ),
    ]
