# Generated by Django 5.2 on 2025-05-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_featured_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
